# Executable should be a full path
executable=/home/ltrochelmann/LN-variants/CNN/cluster/condor.sh

# Pass arguments to the executable
arguments  = $(lr)

# Logs
LOGS_DIR=/home/ltrochelmann/LN-variants/logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 250000
request_cpus = 12
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB") && (TARGET.Machine != "g147.internal.cluster.is.localnet") && (TARGET.Machine != "g132.internal.cluster.is.localnet")

queue lr from (
    0.005
    0.01
    0.02
    0.05
    0.1
)
