# Executable should be a full path
executable=/home/ltrochelmann/LN-variants/cluster/multi_gpu/condor.sh

# Hyperparameters are specified in a YAML configuration file
config=/home/ltrochelmann/LN-variants/config/exp_hidden_variance/TR_post-norm_6L_2gpu.yaml

# Queue as many jobs as points in the hyperparameter grid
n_jobs=8

# Pass arguments to the executable
arguments = $(config) $(Process)

# Logs
LOGS_DIR=/home/ltrochelmann/LN-variants/logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 250000
request_cpus = 16
request_gpus = 2
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB") && (TARGET.Machine != "g147.internal.cluster.is.localnet") && (TARGET.Machine != "g132.internal.cluster.is.localnet")

queue $(n_jobs)