# Executable should be a full path
executable=/home/ltrochelmann/LN-variants/non_transformer/cluster/get_hessian.sh

# Hyperparmeters are specified in a YAML configuration file
config=/home/ltrochelmann/LN-variants/non_transformer/config/exp_depth_mlp/MLP_pre-norm_16L_res-scale.json

# Pass arguments to the executable
arguments  = $(config) $(lr)

# Logs
LOGS_DIR=/home/ltrochelmann/LN-variants/logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 32000
request_cpus = 3
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB") && (TARGET.Machine != "g147.internal.cluster.is.localnet") && (TARGET.Machine != "g132.internal.cluster.is.localnet")

# single run
queue lr from (0.1)

