
deterministic: False
seed: 7

cuda_matmul_allow_tf32: True
cudnn_allow_tf32: True

trainset_path: 'YOUR_PATH_HERE'
vocab_size: 50280
seq_len: 2048
sampler: 'random'
sampler_seed: 7
num_workers: 4

eval: True
validset_path: 'YOUR_PATH_HERE'
eval_every_steps: 32

model: 'transformer'
d_model: 512
expand: '8/3'
n_layers: 6
n_heads: 8
mlp_class: 'glu'
tie_embeddings: False
torch_compile: True

weight_init: 'gpt2_res-scale'  # choose from 'gpt2_res-scale', 'gpt2_no-scale', (ablations: 'gpt2_glu-scale', 'gpt2_attn_scale')

ln_config: 'pre-norm'  # choose from 'no-norm', 'pre-norm', 'post-norm', (ablations: 'pre-attn-norm', 'pre-glu-norm', 'post-attn-norm', 'post-glu-norm')
ln_style: 'LayerNorm'  # choose from 'LayerNorm', 'LayerNorm_Simple', 'OnlyAffine', 'DetachNorm'
attn_style: 'Default'  # choose from 'Default', 'QKNorm'
ln_use_shift: True  # whether or not to use the LayerNorm bias parameter if applicable
qknorm_L97: 2048  # for QKNorm temperature initialisation

# note: step budget=token_budget/(seq_len * micro_batch_size * grad_accumulation_steps)
steps_budget: 5340  # choose 70M*20=1.4B tokens by chinchilla scaling law -> Obtain step size as 1.4B/(2048*32*4) = 5340.576...

# note 1: this is micro batch size if grad_accumulation_steps>1
# note 2: with ddp, effective batch size = batch_size * grad_accumulation_steps * ddp_world_size
micro_batch_size: 32  # target batch size: 128
grad_accumulation_steps: 4  # target batch size: 128

# note: choose between {float32, float16, bfloat16}
# note: float16 data type will automatically use a GradScaler
dtype: 'bfloat16'

optim: 'adamw'
fused_optim: True
lr: [2.e-4, 5.e-4, 1.e-3, 2.e-3, 5.e-3, 1.e-2, 2.e-2, 5.e-2]
weight_decay: 0.1
beta1: 0.95  # tied betas
beta2: 0.95
grad_clip: 1.0
eps: 1.e-8

scheduler: 'wsd'
warmup_steps: 320
cooldown_steps: 0.15
lr_start: 1.e-10
lr_end: 0.0
lr_end_pct: null

log_every_steps: 16
print_progress: false

use_wandb: True
wandb_watch: False
wandb_project: 'YOUR_WANDB_HERE'
wandb_dir: 'YOUR_PATH_HERE'
wandb_run_name: 'YOUR_PATH_HERE'
exp_name: 'YOUR_PATH_HERE'
check_existing_wandb_run: False
track_model_update: True
track_grad_norm: True
track_param_update: True
track_softmax: True
track_ln_weights: True

resume: False
resume_step: null
resume_exp_name: null

out_dir: 'YOUR_PATH_HERE'
save_last_checkpoint: True
save_intermediate_checkpoints: False
save_every_steps: null

save_optim: False
save_scheduler: False
save_scaler: False

over_write: False