
# Executable should be a full path
executable=/home/ltrochelmann/LN-variants/cluster/single_gpu/condor.sh

# Hyperparmeters are specified in a YAML configuration file
config=/home/ltrochelmann/LN-variants/config/exp_qknorm/TR_pre-norm_6L_res-scale_qknorm.yaml

# Queue as many jobs as points in the hyperaparameter grid
n_jobs=8

# Pass arguments to the executable
arguments = $(config) $(Process)

# Logs
LOGS_DIR=/home/ltrochelmann/LN-variants/logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 250000
request_cpus = 8
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB") && (TARGET.Machine != "g147.internal.cluster.is.localnet") && (TARGET.Machine != "g132.internal.cluster.is.localnet")
queue $(n_jobs)
