# Executable should be a full path
executable=/home/ltrochelmann/LN-variants/cluster/single_gpu/layer_influence.sh

# Path to .pth checkpoint
ckpt=/fast/ltrochelmann/exp/main/TR_ours_6L_scalarLN/job_idx_1/ckpt_micro_step_21363.pth

# Pass arguments to the executable
arguments = $(ckpt)

# Logs
LOGS_DIR=/home/ltrochelmann/LN-variants/logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 25000
request_cpus = 8
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB") && (TARGET.Machine != "g147.internal.cluster.is.localnet") && (TARGET.Machine != "g132.internal.cluster.is.localnet") && (TARGET.Machine != "g174.internal.cluster.is.localnet")

queue 1
